<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.3" />
    <PackageReference Include="AWSSDK.SSO" Version="4.0.100.15" />
    <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.100.14" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.104.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyMentor.Application\MoneyMentor.Application.csproj" />
    <ProjectReference Include="..\MoneyMentor.Domain\MoneyMentor.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
