namespace MoneyMentor.Application.InputParsing;

internal static class ExpenseCategoryKeywordCatalog
{
    public static readonly ExpenseCategoryKeywordRule[] Rules =
    [
        new(
            "Food Delivery",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "swiggy",
                "zomato",
                "food delivery",
                "ordered food",
                "online food",
                "delivery dinner",
                "delivery lunch"),
            90),
        new(
            "Groceries",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "groceries",
                "grocery",
                "supermarket",
                "kirana",
                "ration",
                "sabzi",
                "sabji",
                "vegetables",
                "veggies",
                "fruits",
                "fruit",
                "doodh",
                "milk",
                "bread",
                "eggs",
                "atta",
                "dal",
                "rice",
                "chawal",
                "oil",
                "local market",
                "blinkit",
                "zepto",
                "bigbasket",
                "dmart"),
            80),
        new(
            "Snacks",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "ice cream",
                "icecream",
                "snack",
                "snacks",
                "chips",
                "chocolate",
                "biscuit",
                "biscuits",
                "chai",
                "tea",
                "coffee",
                "samosa",
                "vadapav",
                "vada pav",
                "pani puri",
                "golgappa"),
            85),
        new(
            "Dining",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "dinner",
                "lunch",
                "breakfast",
                "restaurant",
                "cafe",
                "hotel",
                "khana",
                "meal",
                "food",
                "pizza",
                "burger",
                "biryani",
                "dosa",
                "idli",
                "poha",
                "paratha",
                "roti",
                "thali"),
            70),
        new(
            "Rent",
            ExpenseInputKeywordSets.CreateKeywordSet("rent", "kiraya", "house rent", "flat rent"),
            95),
        new(
            "Fuel",
            ExpenseInputKeywordSets.CreateKeywordSet("petrol", "diesel", "fuel", "cng", "gas station"),
            90),
        new(
            "Transport",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "cab",
                "taxi",
                "uber",
                "ola",
                "auto",
                "rickshaw",
                "bus",
                "metro",
                "train",
                "fare",
                "toll",
                "parking"),
            75),
        new(
            "Utilities",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "electricity",
                "bijli",
                "water bill",
                "paani bill",
                "internet",
                "wifi",
                "broadband",
                "phone bill",
                "mobile bill",
                "recharge",
                "gas cylinder",
                "cylinder",
                "utility",
                "utilities"),
            80),
        new(
            "Shopping",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "amazon",
                "flipkart",
                "myntra",
                "ajio",
                "shopping",
                "clothes",
                "shirt",
                "tshirt",
                "t shirt",
                "shoes",
                "dress",
                "jeans"),
            65),
        new(
            "Healthcare",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "medicine",
                "medicines",
                "medical",
                "doctor",
                "hospital",
                "pharmacy",
                "chemist",
                "dawa",
                "dawai",
                "dentist"),
            80),
        new(
            "Education",
            ExpenseInputKeywordSets.CreateKeywordSet("school", "college", "tuition", "course", "books", "book", "fees", "exam"),
            70),
        new(
            "Entertainment",
            ExpenseInputKeywordSets.CreateKeywordSet(
                "movie",
                "movies",
                "cinema",
                "netflix",
                "spotify",
                "hotstar",
                "prime video",
                "game",
                "gaming",
                "concert"),
            70),
        new(
            "Travel",
            ExpenseInputKeywordSets.CreateKeywordSet("flight", "hotel booking", "vacation", "trip", "travel", "airport", "train ticket", "bus ticket"),
            70),
        new(
            "Fitness",
            ExpenseInputKeywordSets.CreateKeywordSet("gym", "protein powder", "supplement", "supplements", "workout", "fitness"),
            75),
        new(
            "Personal Care",
            ExpenseInputKeywordSets.CreateKeywordSet("salon", "haircut", "parlour", "parlor", "cosmetics", "makeup", "spa"),
            70),
        new(
            "Household",
            ExpenseInputKeywordSets.CreateKeywordSet("cleaning", "detergent", "maid", "furniture", "appliance", "repair", "plumber", "electrician"),
            65),
        new(
            "Bills",
            ExpenseInputKeywordSets.CreateKeywordSet("emi", "loan", "insurance", "premium", "credit card bill", "card bill", "bill"),
            65)
    ];
}

internal sealed record ExpenseCategoryKeywordRule(
    string Category,
    IReadOnlySet<string> Keywords,
    int Priority);
